# Generated by Django 6.0.6 on 2026-06-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
